# Generated by Django 4.1.7 on 2023-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_RestaurantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('Restaurantname', models.CharField(max_length=30)),
                ('locatiion', models.CharField(max_length=30)),
                ('typeofshop', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField()),
                ('no_ofstaff', models.IntegerField()),
                ('auth_person', models.CharField(max_length=30)),
                ('p_email', models.EmailField(max_length=30)),
                ('p_contact', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_RestaurantAccount',
            },
        ),
    ]
