# Generated by Django 4.1.7 on 2023-05-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurantName', models.CharField(max_length=30)),
                ('MenuName', models.CharField(max_length=30)),
                ('MenuItemName', models.CharField(max_length=30)),
                ('Quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('cookingtime', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Fooditem',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Res_id', models.CharField(max_length=30)),
                ('MenuItemName', models.CharField(max_length=30)),
                ('offer', models.CharField(max_length=30)),
                ('satartdate', models.CharField(max_length=30)),
                ('enddate', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Offer',
            },
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('Restaurantname', models.CharField(max_length=30)),
                ('feedback', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
        migrations.CreateModel(
            name='tbl_FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restname', models.CharField(max_length=30)),
                ('MenuName', models.CharField(max_length=30)),
                ('cusine', models.IntegerField()),
                ('origin', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_FoodMenu',
            },
        ),
        migrations.CreateModel(
            name='tbl_RestAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusername', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('restname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('Rest_id', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_RestAdmin',
            },
        ),
        migrations.CreateModel(
            name='tbl_UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('address', models.EmailField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_UserAccount',
            },
        ),
    ]
