# Generated by Django 4.1.7 on 2023-05-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_tbl_restaurantaccount_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_foodmenu',
            name='cusine',
            field=models.CharField(max_length=30),
        ),
    ]
