# Generated by Django 4.1.7 on 2023-05-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_tbl_foodmenu_cusine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='satartdate',
            new_name='startdate',
        ),
    ]
