# Generated by Django 4.1.7 on 2023-05-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_fusername_tbl_restadmin_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_restaurantaccount',
            old_name='locatiion',
            new_name='location',
        ),
    ]
